name: rx_permissions
description: >-
  This package provides a reactive cross-platform (iOS, Android) API
  to request and check permissions for the permission_handler package.
version: 1.2.0
homepage: https://github.com/mi-sch-ka
repository: https://github.com/mi-sch-ka/rx-permissions
issue_tracker: https://github.com/mi-sch-ka/rx-permissions/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # reactive programming: additional capabilities to dart streams and stream-controllers.
  rxdart: ^0.27.7
  # permission handler
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  uses-material-design: false
